version: "1.7"
services:
  worker:
    build: .
    environment:
SESSION_NAME: $SESSION_NAME
BOT_TOKEN: $BOT_TOKEN
BOT_NAME: $BOT_NAME
API_ID: $API_ID
API_HASH: $API_HASH
OWNER_NAME: $OWNER_NAME
ALIVE_NAME: $"ALIVE_NAME
BOT_USERNAME: $BOT_USERNAME
ASSISTANT_NAME: $ASSISTANT_NAME
GROUP_SUPPORT: $GROUP_SUPPORT
UPDATES_CHANNEL: $UPDATES_CHANNEL
SUDO_USERS: $SUDO_USERS
COMMAND_PREFIXES: $COMMAND_PREFIXES
ALIVE_IMG: $ALIVE_IMG
DURATION_LIMIT: $DURATION_LIMIT
IMG_1: $IMG_1
IMG_2: $IMG_2
IMG_3: $IMG_3
ARQ_API_KEY: $ARQ_API_KEY
ARQ_API_URL: $ARQ_API_URL
